### PR TITLE
Restructure COPASI wrapper into Biosimulations_copasi package with CLI and CI

### PR DESCRIPTION
**Pull request by gmarupilla**
- [x] Works with multiple SEDML/SBMLs/TASKS
- [x] Get all SED-ML files with python_libcombine
- [x] Restructure according to simulator docker template
- [x] Create methods for Timecourse (A separate report is created in util.py)
- [x] Test with more complex Archives
- [ ] Verify and finalize the properties JSON
- [x] Write complete tests
   - [x] Fix failing tests and add pytest inside dockerimage

### CODE REVIEW

**Review by jonrkarr — CHANGES_REQUESTED** [review]
The repo and image look good. I think there's just a few minor things that need to be changed (see below).

I pushed a few minor corrections, including fixing the example COMBINE archive for BIOMD0000734 which had some awkward SED-ML.

Regarding the long validation case, I added an option to the validator to control which test cases are verified. I then used this to create short and long unit tests. The former can be used with continuous integration. The latter is useful, but impractical for continuous integration. The latter will be skipped under when run by a CI system.

I think the following changes should be made:

(1) The command line program needs to process the SED-ML reports and save them as CSV files. This was probably overlooked because the SED-ML file for BIOMD0000734 didn't include a report. I have expanded this example to look more like the SED-ML that BioSimulations will generate. These reports can probably be created from 'Time-Course.txt' (the reports should be a subset of the table in this file). The validator unit test now illustrates this failure.

(2) I think the command-line program can create additional simulator-specific reports not specified in the SED-ML files (e.g., 'CLyapTask.txt'). However, these should be ignored by the BioSimulations simulation results storage system.

(3) Some of the details of the algorithms in `properties.json` are copied from my example. I tried to correct this. ~~@moraru can you review the algorithm parameters as well?~~ We should ask the COPASI team to review this as this will control how COPASI is presented to end users. See #25.

(4) I think the DockerHub repo should be renamed to `crbm/biosimulations_copasi` and the tags correspond to the underlying version of COPASI (e.g., 4.27).

(5) I corrected the version to 4.27.214. Please check this is correct.

(6) I think most the secrets for the GitHub actions can be removed.

(7) The dockerimage GitHub workflow should also run the unit tests.

I can re-review after these issues are addressed.  We can ask Bilal to review at that point as well.

**Comment by gmarupilla** [comment]
> The repo and image look good. I think there's just a few minor things that need to be changed (see below).
> 
> I pushed a few minor corrections, including fixing the example COMBINE archive for BIOMD0000734 which had some awkward SED-ML.
> 
> Regarding the long validation case, I added an option to the validator to control which test cases are verified. I then used this to create short and long unit tests. The former can be used with continuous integration. The latter is useful, but impractical for continuous integration. The latter will be skipped under when run by a CI system.
> 
> I think the following changes should be made:
> 
> (1) The command line program needs to process the SED-ML reports and save them as CSV files. This was probably overlooked because the SED-ML file for BIOMD0000734 didn't include a report. I have expanded this example to look more like the SED-ML that BioSimulations will generate. These reports can probably be created from 'Time-Course.txt' (the reports should be a subset of the table in this file). The validator unit test now illustrates this failure.
> 
> (2) I think the command-line program can create additional simulator-specific reports not specified in the SED-ML files (e.g., 'CLyapTask.txt'). However, these should be ignored by the BioSimulations simulation results storage system.
> 
> (3) Some of the details of the algorithms in `properties.json` are copied from my example. I tried to correct this. ~@moraru can you review the algorithm parameters as well?~ We should ask the COPASI team to review this as this will control how COPASI is presented to end users. See #25.
> 
> (4) I think the DockerHub repo should be renamed to `crbm/biosimulations_copasi` and the tags correspond to the underlying version of COPASI (e.g., 4.27).
> 
> (5) I corrected the version to 4.27.214. Please check this is correct.
> 
> (6) I think most the secrets for the GitHub actions can be removed.
> 
> (7) The dockerimage GitHub workflow should also run the unit tests.
> 
> I can re-review after these issues are addressed. We can ask Bilal to review at that point as well.

I made all the suggested changes.  

For adding tests in the docker workflow, we need to have Biosimulations_utils as ready package in PyPI. Currently, in my local machine, I'm installing it using: 
`pip install git+https://github.com/reproducible-biomedical-modeling/Biosimulations_utils.git  ` Which is not the ideal scenario for CI. So, once the package is pushed to PyPI. I'll enable the tests.

**Review by jonrkarr — CHANGES_REQUESTED** [review]
I pushed Biosimulations_utils to PyPI. However, I suggest installing the GitHub version in GitHub actions, at least for now, because the package is still evolving quickly.

(1) The command line program needs to process the SED-ML reports and save them as CSV files. The name of the CSV file should the id the SED report plus the extension `.csv`. The reason for this is that a SED-ML file could specify multiple reports, and the reports need to be saved with unique file names.

This test case highlights the issue:
```
____________________________________________________ CliTestCase.test_one_case_with_validator ____________________________________________________

self = <test_all.CliTestCase testMethod=test_one_case_with_validator>

    @unittest.skipIf(docker is None, 'Docker not available')
    def test_one_case_with_validator(self):
        validator = SimulatorValidator()
        valid_cases, case_exceptions, _ = validator.run('crbm/biosimulations_copasi', 'properties.json',
                                                        test_case_ids=['BIOMD0000000297.omex', ])
>       self.assertGreater(len(valid_cases), 0)
E       AssertionError: 0 not greater than 0

tests/test_all.py:149: AssertionError
-------------------------------------------------------------- Captured stdout call --------------------------------------------------------------
crbm/biosimulations_copasi passed 0 test cases:
  
crbm/biosimulations_copasi failed 1 test cases:
  BIOMD0000000297.omex
    Report /tmp/tmpga3vgk5m/./simulation_1/simulation_1.csv was not created
crbm/biosimulations_copasi skipped 3 test cases:
  BIOMD0000000297.xml
  BIOMD0000000734.omex
  test-bngl.omex
```

(2) The dockerimage GitHub workflow should also run the unit tests.

**Comment by gmarupilla** [comment]
I have made the required changes.

The test case `test_one_case_with_validator` is still failing. It gives 'FileDoesNotExist' error for omex archive. I looked into the installed packages and indeed Biosimulations_utils/simulator/test-cases doesn't contain the omex archives when installed via pip while on Github repo they are present.


Also, we cannot use latest Ubuntu everytime because Ubuntu 20.04 comes pre-installed with python 3.8.2 (latest python) but we cannot use latest python version with copasi.

I even raised the issue regarding this in pycotools repo: https://github.com/CiaranWelsh/pycotools3/issues/5


We can use copasi on python with a version up to 3.7. Beyond that, `python_copasi` won't install.

**Comment by jonrkarr** [comment]
I'll add the test cases to the PyPI package.

The images can use any base OS. This is one of the major benefits of Docker. The Docker images abstract away the details of each simulator from the BioSimulations system as a whole.

Regarding the COPASI image, any version of Python is fine. I don't see a reason why Python 3.8 is necessary. You can use Python3.7 with the latest version of Ubuntu or an earlier version.

**Comment by gmarupilla** [comment]
Thanks for the quick fix, Jonathan. Now, the test cases are getting downloaded while installing Biosimulation_utils as a pip package. But, the validation still doesn't pass. Seems like it's trying to assert `{"FeDuo", "time"}` with `{"FeDuo", "time", " "}`. Where `{"FeDuo", "time"}` are the variables parsed from SEDML files inside testing.py (From Biosimulations_utils package) and `{"FeDuo", "time", " "}` are the columns from the result CSV after reading it as DataFrame.

I found out, the default report generation of COPASI adds a trailing `,` after each line, which any CSV parser (including Pandas') parses as additional column and hence the test case fails.

I'm not sure if this can be avoided by modifying SEDML in some way. So, do I need to change the default report format for COPASI? Or do we need to change the line separator while importing CSV as DataFrame?

**Comment by jonrkarr** [comment]
I think your Python program should strip the extra `,` from the end of each line to create output that is compatible with that of other programs.

I think its important to force standardization on the images to avoid the need to deal with this in other parts of the BioSimulations framework.

**Comment by gmarupilla** [comment]
I made the required changes, all the assets are passing but the test is failing because it cannot delete the temp folder (gives Permission denied error).

I tried to investigate the issue. Seems like while running the docker image, we're not passing down the host user and group details to the container. That's why it's saving the report CSVs as the root user, due to which the host user cannot delete the file.

**Comment by jonrkarr** [comment]
Yes, this results from Docker running as root. The other images have the same issue. This is one of the problems that Singularity address to make containers suitable for shared compute clusters.

One way to work around this is to pre-create the necessary temporary directories before the Docker container is executed. I don't think this is an issue in GitHub CI because I think this runs as root.

**Comment by gmarupilla** [comment]
It's not the temp directory that's not getting deleted. It's the result file as far as I can see, temp directory while testing is created on the host. But the result files are written by docker. So when the execution completes, the host is able to delete the directories but gives errors for the files created by docker.

**Comment by jonrkarr** [comment]
I've worked around this by creating and touching the paths that should be created before the container is run. Locally, tests can also be run as root. For me this is fine because I work in a VM.

**Comment by gmarupilla** [comment]
@jonrkarr I made the required changes, you can review and merge the PR.

**Review by jonrkarr — APPROVED** [review]
The command-line program, Docker image, and simulation results look good. 

I just fixed the capitalization of COPASI and added assertions for the row and column labels. The validator already does this, but I think its helpful to include this in the tests for this package because they're helpful debugging hints. I also removed the comments from the Dockerfile which are no longer needed since you're using the python:3.7 image instead of Ubuntu.

**Pull request merged**
